//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip()
        {
            this.isActive = false;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ShortcutKey { get; set; }
        public string GifUri { get; set; }
        public string VdeoUri { get; set; }
        public string HelpUri { get; set; }
        public Nullable<int> Version { get; set; }
        public string ImageUri { get; set; }
        public string UiTarget { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string LastEditedBy { get; set; }
        public string MinVSVersion { get; set; }
        public string MaxVSVersion { get; set; }
    }
}
